common:
    arch: LNet54_2_se
    workers: 1
    batch_size: 32
    epochs: 200
    policy: "step"
    base_lr: 0.01
    momentum: 0.9
    weight_decay: 0.0001
    print_freq: 10
    save_path: checkpoints/lnet54-2-se-nofc_bs32
