common:
    arch: se_resnet152
    workers: 1
    batch_size: 32

    epochs: 100
    policy: "step"
    base_lr: 0.05
    momentum: 0.9
    weight_decay: 0.0001

    print_freq: 20
    save_path: checkpoints/se_resnet152_bs32
